name: 0 */3 * * *
on:
  schedule:
  - cron: 0 */3 * * *
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        table_path:
        - simple_data.stg_finance.f_revenuecat_event
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: pip
    - run: pip install -r requirements.txt
    - name: run main
      env:
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_USER_META: ${{ secrets.SNOWFLAKE_USER_META }}
        SNOWFLAKE_PASSWORD_META: ${{ secrets.SNOWFLAKE_PASSWORD_META }}
        SNOWFLAKE_ACCOUNT_META: ${{ secrets.SNOWFLAKE_ACCOUNT_META }}
        SNOWFLAKE_WAREHOUSE_META: ${{ secrets.SNOWFLAKE_WAREHOUSE_META }}
        PASSWORD_EMAIL: ${{ secrets.PASSWORD_EMAIL }}
        SEND_EMAIL: ${{ secrets.SEND_EMAIL }}
        CHANNEL: ${{ secrets.CHANNEL }}
        COMPANY: ${{ secrets.COMPANY }}
        EMAILS: ${{ secrets.EMAILS }}
        API_KEY_ATLAN: ${{ secrets.API_KEY_ATLAN }}
        DOMMEN_ATLAN: ${{ secrets.DOMMEN_ATLAN }}
        SODA_CLOUD: ${{ secrets.SODA_CLOUD }}
        API_KEY_ID_SODA: ${{ secrets.API_KEY_ID_SODA }}
        API_KEY_SECRET_SODA: ${{ secrets.API_KEY_SECRET_SODA }}
        PATH_TO_TABLE: ${{ matrix.table_path }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        SCHEDULE: 0 */3 * * *
        ALWAYS_SEND: 'False'
        TEST_CHANNEL: ${{ secrets.TEST_CHANNEL }}
      run: 'python3 main.py

        '
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.table_path }}
        retention-days: '10'
        path: temp/*
