name: test_merge
on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: 'python -m pip install --upgrade pip
        pip install pytest

        '
    - name:  pytest tests/tests.py
      run: ' pytest tests/tests.py'
